sudo: false
language: python
python:
- '3.4'
addons:
  postgresql: '9.3'
env:
- SQLALCHEMY_DATABASE_URI=postgresql://postgres:@localhost:5433/test_notifications_admin
install:
- bundle install
- pip install -r requirements_for_test.txt
env:
  secure: jT9BIioqBMkOdLZhU+WJNdnRJ+06G7qUx4QqEVldp96dJwmWpPEvA0XbitdnQt/WXYkpMlDbgSApvvGj2ZNvdpowRRe5HFX8D2Udhi2g9+cXgKrQxH6zv0evJyQLOjCINW6KtgMCJ5wkYR3qQ4BQawlDt6ecpmeboKTmvs2W8jZ09aV4IKKvdd7BwFon10QVPF5ny10G83unLtKnKgRMjSSLnaEiA78pE/LSUkekK4mhmtl+yfQf60cIuQGcN9NCYIt5PrdYYyMkbUaht9ykwL2C11sp5JYPClI9k6lrlpGJCdL9wbJwejGhR/pEqwJ4tKK8Zv+mngmkbzE6fd5ehuRMnIUAifG4t3p6WbhKwY5pJsdVyPgWcRSPXOJA7yEcAeTAvWcC++6mCIFBeMxt/yQNw02jkFHeNKRh2twTRvr4xWZHq9FsVxTEVz89OOuue3IkkyDNmVusGJ9+AVRIn9Oa+U/r3bDnrs7jz+meSwb82GZUBzFpUe2pe8qeBE572Ay7yHB73VHUgp/2A1qkZ4SnTjTpMbnS5RdXTgwtMkOs5MLZgteCVxFL3sHcr9e/B3UIUnzKUSPXXOjHyDxBwrABWo81V9Vp2IPV7P9Ofv8zroudjQxK5MOcbmiPQF+eEB9L4DvkUBNsGxtJ/nmPp6tmN0Xjo0xXVdZCEVj29Og=
before_script:
- psql -c 'create database test_notifications_admin;' -U postgres
after_success:
- ./scripts/trigger-dependent-build.sh
script:
- ./scripts/run_tests.sh
notifications:
  slack:
    rooms:
      secure: A6n6Gdz3dsE+KQcOd1nWTvdjOF2YbgItT1E40r25poG6p04WHd8qWtC4T2FuZaxPN/TQdKr/dKa/WCkmiEdxT5O0SOwAnAD3u6Fn2nthoI4M5916UrK1ZrqupvnFPSQc8Ivh51PGkcmB4wrb0ylRhMB94RmLcUZcVuXLDx57GO8bPFyLC3E9bgcVVFWaX45sKs74sBSQWi9EBbzHIuduLdjIpW7wX07dA++HlY14W5WgiurmiYohfP11VdAMmMxJs2WdWk16O/qy0HZXaldNIsSnuDBkhAZOMeSrcvp+62yOiN8jK0nSa1IRr3IoUkITdC9YGys3xFJb8gyIQE9T3hUnTYAKCcgsgpVFS6UzsRN42JUAJ8rFTgK9/J299yTk4lqL8uWzcV1QcKXIPNoG0QfqkmlB9B1fKbXuE/KkPEXPCKAcVQpCzEon09FgTCrlVZqJ6HxQonnLcPlIpVzWHAFokLZVHLAFMKYJnGBcZ6zaRK5pdc1babcOXMIPBC8j028G5bhBaCviDvZlimxOsUK1sJTpjzMU0tBQZa8lI+0O5otvMKiX8jPyaedjVvUmsftF2O5FH5nz2ofJC7BThb76/Tac2pNTCn0pWiVz9wi/YXALOMdIzkYgHnyZdEqAjRlpFwZuOrzR6MuvivBebPxjYaRWzCjOeC1uIwz+48E=
deploy:
  provider: heroku
  api_key:
    secure: Er2XHDpbwKvc0empImhEQCvSZ5o2meC3o6nGNAy3WoD3Vc2UiPxn7+OkQKYN0Bt/5BTQcYeGrsM1vDSt/pYsODCuzujkewB94NEJ/zN9hArCuYAEte/r9tAm4faaMIYBU54HAUqFOz/jYo/zzpFiznnVzGlcJXTbmgjXWBLtx5UBeb/cRyP0ErwbjIclv9rBScXiinflo4aSAhJn1sMwbh4646HCjmGm7NVLIM7sooReBHqpuH7qD1bcmssTIea2RDBhy2Qfi6jMbvlRUqPbhNMtQaZrPg6u4/3riYt61ZvrGFtHVcbprpX+IVIdYqEoDq4N0qAKkEVXu+mjfPQjk5+xFguqJ94j6mPrcW4p95SbwRMk/qXZhjOiV3N4mucghbF8dYjsFDSXf9fe7gc4NFAlQK70kS4OBGFQ3nkaHXCkLT4yvKK4vsAHMeNQrVnECHdRRPPP4y7srbQCTdfdJMnJ+tuUpkpNbj9U2DzTTGwEuGiWGwWsNU9tQ7pAftbzsD3gRy7b9iYXnriz8l7yMxN6aoIL4lV3PWi3drHuLHxPHeVnetfK/gDx55Lb5WXNeX2VZmLp9kSJx32OdKF2yhvI6uOYJKR6weTJkIYEBK9+kB5+0aOpG83Dvn8Co6I9nkdMt8CGK2UOX1X1IrgXrtIMSOkVVLPPPWqTaUiJXHg=
  app: notifications-admin
  on:
    repo: alphagov/notifications-admin
  run:
    - python app.py db upgrade
- provider: s3
  access_key_id: AKIAI37IS2VAC5PJHHDA
  secret_access_key: &1
    secure: Ztj8D7S7YQAarbdF7T0XFRNDTzop/vrPdZL5e07L7c5TwXqr3Dy2ZcKDZMCDTkjgsx7cVu5OhtRtG/+k2FbfQqDrvyYI6jssSIokTdWdXLVdbtI4BqgEcoxouLgOIgAdqV1BzqfDVPiu9GUIlDIT1f/VjU3sRQGw5ioWXvwYkdzuqI+bXir8/Y1Vzcupqn7BoP2iyhB3FZ4HxHUjqau1g2g++17jfFgIghg6zaAuLWB3raGjWo6H+BvieZqIma0p643rs39fXjr8lIfvP8FGlKSTXzQX2+KGSjdTJx64KRSdO9iFuiedL1dkSbEXNebh2Q9M1FDdWmrO6PsgRFtQI0Kgy/3CATqlEEOjgPjBSyDIfzPGE+HBDyTId1hy2u/0BekDQRfJeCikV8ebcWRTjyr+j2EvUhhmDDQrZusyz25UA7IuurVEPVT/mzAEFseu4dMcKTlmk4Jo8eFqcrtyLcFpH7QPCwwIj7MjUlzwepvgxuhGR/UHIMDH7R8QLVuT3beE+AyumyJb0QHt4yLlg6WHxaK5ayNQBVm20yD64dRKQsEMvdewVz9fLhoa4sV5PNqBn0yghdiKnQA2XynBen8hEbpuraN/wvX9z+STMoR/fG33X2XwAn3f08qO1RzMy4mxsq75tkD8yR8i/JAMtawARuBzSk3asXol/EtwlbQ=
  local_dir: dpl_cd_upload
  skip_cleanup: true
  region: eu-west-1
  on: &2
    repo: alphagov/notifications-admin
  bucket: notifications-admin-codedeploy
- provider: codedeploy
  access_key_id: AKIAI37IS2VAC5PJHHDA
  secret_access_key: *1
  bucket: notifications-admin-codedeploy
  key: notifications-admin.zip
  bundle_type: zip
  application: notifications-admin
  deployment_group: notifications_admin_deployment_group
  region: eu-west-1
  on: *2
before_deploy:
- zip -r notifications-admin *
- mkdir -p dpl_cd_upload
- mv notifications-admin.zip dpl_cd_upload/notifications-admin.zip